'use strict';

// ── Prompt categories ─────────────────────────────────────────────────────────
//
// Each category has an id, a display label, an emoji, and an array of prompts.
// The server picks one prompt at random from the chosen category each round.
// Passing category 'all' picks from every prompt across all categories.
//
const CATEGORIES = [
  {
    id:     'all',
    label:  'All Categories',
    emoji:  '🎲',
  },
  {
    id:     'food',
    label:  'Food & Drink',
    emoji:  '🍕',
    prompts: [
      'Name a fruit',
      'Name a vegetable',
      'Name a citrus fruit',
      'Name a berry',
      'Name a tropical fruit',
      'Name a fast food restaurant',
      'Name a pizza topping',
      'Name a breakfast food',
      'Name a snack food',
      'Name a type of pasta',
      'Name a sandwich filling',
      'Name a salad ingredient',
      'Name a dessert',
      'Name an ice cream flavour',
      'Name a type of cake',
      'Name a fizzy drink',
      'Name a hot drink',
      'Name a type of cheese',
      'Name something you put on toast',
      'Name a condiment',
      'Name a type of cuisine',
      'Name a spice or herb',
      'Name something you find in a sushi restaurant',
      'Name a BBQ food',
      'Name a food that is orange',
      'Name a food that is green',
      'Name a food you eat with your hands',
      'Name a soup',
      'Name something you dip chips in',
      'Name a food that comes in a tin',
      'Name a type of bread',
      'Name a pasta sauce',
      'Name a cocktail',
      'Name something you eat at a cinema',
      'Name a type of biscuit or cookie',
      'Name a food you put in a salad',
      'Name a street food',
      'Name a food people eat on New Year\'s Eve',
      'Name a food you only eat on special occasions',
      'Name a food that goes with peanut butter',
      'Name something you might have for lunch',
      'Name a type of noodle dish',
      'Name a food that has cheese in it',
      'Name a famous chocolate bar',
      'Name a breakfast cereal',
      'Name a food that is crunchy',
      'Name a food that is soft',
      'Name something found in a Mexican dish',
      'Name a popular takeaway food',
      'Name something you season food with',
    ],
  },
  {
    id:     'nature',
    label:  'Nature & Science',
    emoji:  '🌍',
    prompts: [
      'Name a country in Europe',
      'Name a country in Asia',
      'Name a country in South America',
      'Name an ocean',
      'Name a type of weather',
      'Name an animal that lives in the ocean',
      'Name a jungle animal',
      'Name a farm animal',
      'Name a bird',
      'Name an insect',
      'Name something you find in a forest',
      'Name a type of tree',
      'Name a flower',
      'Name a planet in our solar system',
      'Name a type of rock or gemstone',
      'Name a natural disaster',
      'Name something you see in the sky at night',
      'Name a continent',
      'Name a famous mountain',
      'Name a type of cloud',
      'Name a season',
      'Name something you find at the bottom of the sea',
      'Name a reptile',
      'Name a type of fish',
      'Name a nocturnal animal',
      'Name an endangered animal',
      'Name a dog breed',
      'Name a cat breed',
      'Name a type of bear',
      'Name a large cat',
      'Name an animal with a long neck',
      'Name an animal with a shell',
      'Name a type of shark',
      'Name a small insect',
      'Name a type of snake',
      'Name a famous river',
      'Name a famous desert',
      'Name a type of forest',
      'Name something a plant needs to grow',
      'Name a type of storm',
      'Name a thing you find on a beach',
      'Name an animal that hibernates',
      'Name a primate',
      'Name a marsupial',
      'Name a type of whale',
      'Name something that lives underground',
      'Name a planet you can see without a telescope',
      'Name something found in space',
      'Name a type of volcano',
      'Name an animal that migrates',
    ],
  },
  {
    id:     'entertainment',
    label:  'Entertainment',
    emoji:  '🎬',
    prompts: [
      'Name a movie genre',
      'Name a TV show everyone has seen',
      'Name a streaming service',
      'Name a Disney movie',
      'Name a Pixar movie',
      'Name a superhero',
      'Name a Marvel character',
      'Name a DC character',
      'Name a famous villain',
      'Name a cartoon character',
      'Name a type of dance',
      'Name a musical instrument',
      'Name a type of music',
      'Name a genre of book',
      'Name a famous fictional robot',
      'Name a decade known for its music',
      'Name a podcast topic',
      'Name a type of video game',
      'Name a famous movie franchise',
      'Name a romantic movie',
      'Name a horror movie monster',
      'Name a famous TV detective',
      'Name a film set in space',
      'Name a famous animated villain',
      'Name a reality TV show',
      'Name a talent competition show',
      'Name a crime drama series',
      'Name a sitcom from the 90s',
      'Name a famous movie director',
      'Name a famous fictional wizard',
      'Name a classic fairy tale',
      'Name a famous book character',
      'Name a famous fictional spy',
      'Name something a DJ uses',
      'Name a music festival',
      'Name a type of concert venue',
      'Name a famous musical',
      'Name a genre of anime',
      'Name a fictional universe from a movie',
      'Name a famous voice actor character',
      'Name a famous catchphrase from a TV show',
      'Name a classic video game character',
      'Name a war movie',
      'Name a comedy film',
      'Name a famous movie sequel',
      'Name a famous movie based on a book',
      'Name a foreign language film',
      'Name a famous quote from a movie',
      'Name a type of documentary',
      'Name something you find at a film premiere',
    ],
  },
  {
    id:     'sports',
    label:  'Sports & Games',
    emoji:  '⚽',
    prompts: [
      'Name a sport',
      'Name an Olympic sport',
      'Name a sport played with a ball',
      'Name a water sport',
      'Name a winter sport',
      'Name a combat sport',
      'Name a racket sport',
      'Name a board game',
      'Name a card game',
      'Name a video game console',
      'Name a famous football club',
      'Name a famous sports brand',
      'Name a famous athlete',
      'Name a team sport',
      'Name an individual sport',
      'Name something you find in a gym',
      'Name a piece of sports equipment',
      'Name a golf term',
      'Name a cricket position',
      'Name a famous tennis tournament',
      'Name something a referee does',
      'Name a famous sports stadium',
      'Name a sport with a net',
      'Name a sport where you need a helmet',
      'Name something you do to warm up',
      'Name a famous Formula 1 driver',
      'Name a type of race',
      'Name a sport played on a court',
      'Name a sport played on ice',
      'Name something you find in a swimming pool',
      'Name a position in football',
      'Name a famous boxing match',
      'Name a type of gymnastics move',
      'Name a sport where you use a stick',
      'Name a famous chess move',
      'Name a card game for two players',
      'Name a playground game',
      'Name a party game',
      'Name a game with dice',
      'Name something you need for camping and hiking',
      'Name a type of yoga pose',
      'Name a famous skateboarding trick',
      'Name a sport with a goal',
      'Name a sport where you score points with a ball',
      'Name something in a sports changing room',
      'Name a famous sports award',
      'Name a dangerous sport',
      'Name a sport with a bat',
      'Name a sport you can do alone',
      'Name something fans do at a sports match',
    ],
  },
  {
    id:     'everyday',
    label:  'Everyday Life',
    emoji:  '🏠',
    prompts: [
      'Name something you bring to the beach',
      'Name something you find in a kitchen',
      'Name something in a backpack',
      'Name something you find in a bathroom',
      'Name something you find in a bedroom',
      'Name something you find in an office',
      'Name something in a first aid kit',
      'Name something you find at a petrol station',
      'Name something you do on a Sunday morning',
      'Name something you do before bed',
      'Name something you do in the morning',
      'Name a chore people hate doing',
      'Name something you take on a flight',
      'Name something you keep in your wallet',
      'Name something you buy at a supermarket every week',
      'Name a reason someone might be late',
      'Name something people do when they\'re bored',
      'Name a sound you hear in a city',
      'Name something you do when you\'re sick',
      'Name a thing people collect as a hobby',
      'Name something you find in a junk drawer',
      'Name a type of bag',
      'Name something that comes in a box',
      'Name something you throw away every day',
      'Name a reason to call in sick',
      'Name something you do on a rainy day',
      'Name a household appliance',
      'Name something in a living room',
      'Name a tool you find in a garage',
      'Name something you do on a long car journey',
      'Name a reason people go to the doctor',
      'Name a type of shop',
      'Name something people argue about at home',
      'Name something that always goes missing',
      'Name something kids don\'t want to do',
      'Name a reason to stay home from school',
      'Name something you do on a Friday night',
      'Name something you forget to pack when travelling',
      'Name something you leave in your car',
      'Name a habit people try to break',
      'Name an app people use every day',
      'Name a thing you check on your phone first thing',
      'Name something you need for a road trip',
      'Name something that breaks easily',
      'Name something everyone owns but rarely uses',
      'Name a thing you do when you get home from work',
      'Name a reason to do laundry immediately',
      'Name something you need to remember on bin day',
      'Name something you find on a desk',
      'Name a reason someone might move house',
    ],
  },
  {
    id:     'popculture',
    label:  'Pop Culture',
    emoji:  '🌟',
    prompts: [
      'Name a social media app',
      'Name a famous YouTuber',
      'Name a famous TikTok trend',
      'Name a popular meme format',
      'Name a famous celebrity couple',
      'Name a fashion brand',
      'Name a luxury brand',
      'Name a famous model',
      'Name a famous comedian',
      'Name an internet slang word',
      'Name a famous award show',
      'Name a famous red carpet look',
      'Name a celebrity known for cooking',
      'Name a famous TV host',
      'Name a famous pop star',
      'Name a famous rapper',
      'Name a famous rock band',
      'Name a famous boy band',
      'Name a famous girl group',
      'Name a celebrity known for a meltdown',
      'Name a viral video trend',
      'Name a popular fashion trend from the 2010s',
      'Name a fashion trend that came back',
      'Name a brand everyone wore as a teenager',
      'Name a famous Hollywood couple',
      'Name a celebrity turned politician',
      'Name a famous sports celebrity',
      'Name a famous talk show',
      'Name a famous late night host',
      'Name a celebrity with a famous catchphrase',
      'Name a celebrity famous for their hair',
      'Name a celebrity famous for their laugh',
      'Name an app that became famous overnight',
      'Name a famous collab between two artists',
      'Name a headline-grabbing celebrity moment',
      'Name a celebrity with a famous sibling',
      'Name a famous celebrity chef',
      'Name a celebrity turned author',
      'Name a celebrity known for their fashion line',
      'Name a pop song everyone knows the words to',
      'Name a meme from the early internet',
      'Name a catchphrase from an advert',
      'Name something that was hugely hyped and flopped',
      'Name a famous podcast host',
      'Name a famous magazine',
      'Name a celebrity with a famous feud',
      'Name a sports celebrity known off the pitch',
      'Name a brand ambassador everyone recognises',
      'Name a celebrity baby name',
      'Name a famous celebrity comeback',
    ],
  },
  {
    id:     'random',
    label:  'Random & Fun',
    emoji:  '✨',
    prompts: [
      'Name something that is always cold',
      'Name something that is always hot',
      'Name something that makes a loud noise',
      'Name something red',
      'Name something round',
      'Name something that can fly',
      'Name something you do when you\'re nervous',
      'Name something you do when you\'re happy',
      'Name a word that rhymes with "cat"',
      'Name a word that rhymes with "night"',
      'Name something that gets better with age',
      'Name something you should never do on a first date',
      'Name a bad habit',
      'Name something people are afraid of',
      'Name something that makes you smile',
      'Name a superpower you\'d want',
      'Name something you\'d find on a deserted island',
      'Name something you\'d save in a fire',
      'Name a childhood toy',
      'Name something that reminds you of summer',
      'Name something that reminds you of winter',
      'Name something that everyone owns',
      'Name something that goes faster over time',
      'Name something that never goes out of style',
      'Name a sign that someone is tired',
      'Name something that was better when you were a kid',
      'Name something you\'d put in a time capsule',
      'Name a thing that people lie about',
      'Name a sign that you\'re getting old',
      'Name a way to waste time',
      'Name something that always takes longer than expected',
      'Name something people say at a party',
      'Name a thing you only do when no one is watching',
      'Name something you regret buying',
      'Name a first-world problem',
      'Name something that always happens at the worst time',
      'Name something satisfying to do',
      'Name something that costs way too much',
      'Name something fun to do in the rain',
      'Name a thing that makes you feel nostalgic',
      'Name something you\'d do with a million pounds',
      'Name a rule you always break',
      'Name something a grandparent might say',
      'Name something kids say that makes no sense',
      'Name a thing adults pretend to enjoy',
      'Name something you say you\'ll do but never do',
      'Name a thing everyone secretly loves',
      'Name a word that sounds funny',
      'Name a thing you\'d do on a lazy day',
      'Name something you\'d wish for from a genie',
    ],
  },
];

// Build a flat "all" prompts array from every category prompt list.
const ALL_PROMPTS = CATEGORIES.filter(c => c.id !== 'all').flatMap(c => c.prompts);

/**
 * Returns the valid category ids (including 'all').
 */
const VALID_CATEGORY_IDS = CATEGORIES.map(c => c.id);

/**
 * Returns a random prompt from the given category id.
 * Falls back to picking from all prompts if the id is unknown or 'all'.
 */
function pickPrompt(categoryId) {
  const category = CATEGORIES.find(c => c.id === categoryId && c.id !== 'all');
  const pool = category ? category.prompts : ALL_PROMPTS;
  return pool[Math.floor(Math.random() * pool.length)];
}

module.exports = { CATEGORIES, VALID_CATEGORY_IDS, pickPrompt };
